stat mountPoint;
mkdir mountPoint/dir1;
mkdir mountPoint/dir2;
mkdir mountPoint/dir3;
mkdir mountPoint/dir4;
mkdir mountPoint/dir1/dir11;
mkdir mountPoint/dir1/dir12;
rmdir mountPoint/dir2;
mkdir mountPoint/dir1/dir13;
touch mountPoint/dir1/file1;
touch mountPoint/dir1/file2;
# touch mountPoint/CONTENTFILE;
echo "***************************";
echo "ls -l mountPoint";
ls -l mountPoint;
echo "***************************";
echo "ls -l mountPoint/dir1";
ls -l mountPoint/dir1;
echo "***************************";
echo "ls -l mountPoint/dir3";
ls -l mountPoint/dir3;
echo "***************************";
echo "Wrote 'THIS IS FILE DATA' to CONTENTFILE";
echo "THIS IS FILE DATA" > mountPoint/CONTENTFILE;
echo "This is the content of CONTENTFILE\n";
cat mountPoint/CONTENTFILE;
cat README.md > mountPoint/NEW-README-COPY.md;
